### ISSUE TITLE
Missing color-convert?

### ISSUE THREAD

**Issue by gregg098** [ryanjohnsontv/node-red-contrib-inovelli-notification-calculator#1]
I'm running NodeRed on Docker (image: nodered/node-red:latest), and after installing this module, it showed an error in the pallete manager saying it was missing color-convert.  

`Error: Cannot find module 'color-convert' (line:2)`

I tried manually installing this via npm, but that didn't work.  Any ideas?

**Comment by gregg098** [comment]
Right after I posted this I looked in the pallete manager for a color convert module and sure enough it was there.  After installing node-red-contrib-color-convert inside of Node Red, everything now works. 

Can you add the pre-requisite of installing node-red-contrib-color-convert to the instructions?

Thanks for the work on this. Works great now.

**Comment by ryanjohnsontv** [comment]
My mistake, I didn't move it out of devDependency section! I just pushed a fix which should reflect very soon in Node Red. In the future, color-convert will now be added automatically when adding this to Node Red. Thanks so much for pointing this out!
