### ISSUE TITLE
Unable to clear notifications

### ISSUE THREAD

**Issue by Hilo4321** [ryanjohnsontv/node-red-contrib-inovelli-notification-calculator#2]
Hi,

It seems I can't clear the notification using the "off" options.

See here, where it sent a color to the switch. I was using the previous implementation of the node before.

![image](https://user-images.githubusercontent.com/52421483/114117618-b0075700-98ac-11eb-8165-e22e9ff485ed.png)

Cheers and thanks!

**Comment by ryanjohnsontv** [comment]
Originally when a value was 0 it was not not included in the message output which is a bug that should be fixed in 0.0.5. When you get the chance can you update and see if that fixes this issue?

**Comment by Hilo4321** [comment]
Cheers, thanks Ryan! Also fixed the issue using extreme ends of the color (0 and 360).
