### ISSUE TITLE
TypeError: Cannot read property 'zwave' of undefined

### ISSUE THREAD

**Issue by Hilo4321** [ryanjohnsontv/node-red-contrib-inovelli-notification-calculator#5]
Hi again,

I came across some odd behavior, and am getting this error.

I can make this work if I inject directly with a timestamp, but if I pass through another node first I get the error. Bottom two message are from the appropriate debug node in this image. 

![image](https://user-images.githubusercontent.com/52421483/114591494-8c973000-9c4f-11eb-9255-33a88987dc02.png)

Let me know if I can provide anything else, and thanks again!

**Comment by ryanjohnsontv** [comment]
I managed to reproduce this on my end, seems to be when the node receives a message without a payload. I'll try to fix ASAP and publish a new version!

**Comment by Hilo4321** [comment]
Cheers! Looks like I went the wrong direction with my troubleshooting.

**Comment by ryanjohnsontv** [comment]
Just published v0.0.10, when you get the chance can you update and let me know if that fixed your issue?

**Comment by Hilo4321** [comment]
Do you know how to trigger the palette to show the update?

**Comment by ryanjohnsontv** [comment]
I typically search for the node, or just "inovelli", in Node Red under "Manage Palette" and in the "Install" tab, then click the "Refresh module list" button, that seems to scan for updates and make them available back under the "Nodes" tab
![image](https://user-images.githubusercontent.com/43426700/114616371-6469fa00-9c6c-11eb-8f6a-3950c9b8c0c8.png)
![image](https://user-images.githubusercontent.com/43426700/114616478-8794a980-9c6c-11eb-9f12-9a34b4f092ef.png)

**Comment by Hilo4321** [comment]
No luck, I'll follow up when I can update.

**Comment by Hilo4321** [comment]
Looks good. Thank you!
